//! The impl matrices — generated by `batch-impl` (the showcase layer).
//!
//! Two entry points: `batch_impl_only` for traits whose methods need
//! directives (the trait is imported, so the spec names it directly; the
//! `#crate::tower::X:` path prefix is only kept for parameterless traits,
//! whose spec syntax cannot carry a trait name — `Real`, `ComplexField`,
//! `BilinearForm`, `EuclideanSpace`, `AffineSpace`), and `batch_trait!` for
//! marker levels and simple methods, which need neither directives nor a
//! duplicated signature-source trait.
//!
//! Feature gating: `primitives`/`tuples`/`option`/`complex`/`analytics` are
//! bare-core (no_std); `containers` needs `alloc` (Vec/String/Box); `maps`
//! (HashMap/HashSet) needs `std`.

pub(crate) mod analytics;
pub(crate) mod complex;
#[cfg(feature = "alloc")]
pub(crate) mod containers;
pub(crate) mod extended;
#[cfg(feature = "std")]
pub(crate) mod maps;
pub(crate) mod option;
pub(crate) mod primitives;
pub(crate) mod quaternion;
pub(crate) mod tuples;
