//! The impl matrices — generated by `batch-impl` (the showcase layer).
//!
//! One DSL block per trait, with the additive/multiplicative sides merged
//! and per-type identity elements riding in directive bodies. The trait
//! definitions live in [`crate::tower`] (single source of truth); each block
//! here references them via the `#crate::tower::X:` path prefix and copies
//! method signatures from a local signature-source `trait` item that the
//! macro drops.
//!
//! Feature gating: `primitives`/`tuples`/`option`/`complex`/`analytics` are
//! bare-core (no_std); `containers` needs `alloc` (Vec/String/Box); `maps`
//! (HashMap/HashSet) needs `std`.

pub(crate) mod analytics;
pub(crate) mod complex;
#[cfg(feature = "alloc")]
pub(crate) mod containers;
pub(crate) mod extended;
#[cfg(feature = "std")]
pub(crate) mod maps;
pub(crate) mod option;
pub(crate) mod primitives;
pub(crate) mod quaternion;
pub(crate) mod tuples;
