//! The impl matrices — generated by `batch-impl` (the showcase layer).
//!
//! Three entry points, in decreasing preference:
//!
//! - **hand-written `impl`s** — bulky algorithm bodies (the Hamiltonian
//!   product, extended euclid, component algebras) read better as plain
//!   `impl`s (`complex.rs`, `quaternion.rs`, `modn.rs`, `arrays.rs`);
//! - **`batch_trait!`** — everything simple: marker levels, one-line method
//!   bodies, associated types, smart-pointer shape templates (the bulk);
//! - **`batch_impl_only`** — only where the directive system earns its keep:
//!   `tuples.rs`'s variadic-repeat component matrix (per-arity generation no
//!   other form expresses) and `SubsetOf`'s shared `T`-parameterized bodies
//!   (13 entries, three bodies — zero duplication).
//!
//! Feature gating: `primitives`/`tuples`/`option`/`complex`/`analytics` are
//! bare-core (no_std); `containers` needs `alloc` (Vec/String/Box); `maps`
//! (HashMap/HashSet) needs `std`.

pub(crate) mod analytics;
pub(crate) mod arrays;
pub(crate) mod complex;
#[cfg(feature = "alloc")]
pub(crate) mod containers;
pub(crate) mod extended;
#[cfg(feature = "std")]
pub(crate) mod maps;
pub(crate) mod modn;
pub(crate) mod option;
pub(crate) mod primitives;
pub(crate) mod quaternion;
pub(crate) mod tuples;
