//! The primitive numeric matrix (v0.1 core) — generated by batch-impl.
//!
//! 15 types (`@num` + `bool` as the field F₂) × every additive/multiplicative
//! level: one `#[batch_impl_only(...)]` block per trait (the additive and
//! multiplicative sides live in the same block), and every method body is
//! written exactly once — the matrix supplies the quantity. The leading
//! `#crate::tower::X:` is the external trait path (the impls reference the
//! real trait, not a local copy); the trailing `trait` item is a signature
//! source only (the `#` directives copy method signatures from it), which
//! `batch_impl_only` drops and never re-emits.
//!
//! Integer operations are wrapping (mod 2^N): under `Additive`, `u8` is the
//! group Z/256Z, which plain `+` would break with an overflow panic in debug
//! builds. Floats use plain arithmetic (an approximate field); `bool` is the
//! exact two-element field (xor as `+`, and as `*`).
//!
//! Impl counts: additive ladder 5 × 15 = 75, multiplicative ladder 3 × 15 =
//! 45, semiring ladder 3 × 15 + Field 3 = 48, module level 15 + 3 vector
//! spaces → 186 impls.

use batch_impl::batch_impl_only;

use crate::op::{Additive, Multiplicative};
use crate::tower::{Field, Monoid};

// ---- one block per trait; the additive and multiplicative sides of a trait
// ---- live in the same block, sharing one path prefix and one signature source ----

#[batch_impl_only(
    #crate::tower::Magma:
    Magma<Additive> [
        [@u*, @i*] #combine{self.wrapping_add(*rhs)},
        @f* #combine{*self + *rhs},
        bool #combine{*self != *rhs}
    ],
    Magma<Multiplicative> [
        [@u*, @i*] #combine{self.wrapping_mul(*rhs)},
        @f* #combine{*self * *rhs},
        bool #combine{*self && *rhs}
    ]
)]
trait Magma<Op: Operator> {
    fn combine(&self, rhs: &Self) -> Self;
}

#[batch_impl_only(
    #crate::tower::Semigroup:
    [Semigroup<Additive>,Semigroup<Multiplicative>]^[@num,bool]
)]
trait Semigroup<Op: Operator>: Magma<Op> {}

#[batch_impl_only(
    #crate::tower::Monoid:
    Monoid<Additive> [
        [@u*, @i*] #identity{0},
        @f* #identity{0.},
        bool #identity{false}
    ],
    Monoid<Multiplicative> [
        [@u*, @i*] #identity{1},
        @f* #identity{1.},
        bool #identity{true}
    ]
)]
trait Monoid<Op: Operator>: Semigroup<Op> {
    fn identity() -> Self;
}

// The multiplicative ladder stops at Monoid for the numerics: integers have
// no multiplicative inverses and floats exclude zero, so Group<Mul> would
// have no inhabitants here.

#[batch_impl_only(
    #crate::tower::Quasigroup:
    Quasigroup<Additive> [@num, bool],
)]
trait Quasigroup<Op: Operator>: Magma<Op> {}

#[batch_impl_only(
    #crate::tower::Loop:
    Loop<Additive> [@num, bool],
)]
trait Loop<Op: Operator>: Quasigroup<Op> + Monoid<Op> {}

#[batch_impl_only(
    #crate::tower::Group:
    Group<Additive> [
        [@u*, @i*] #inverse{self.wrapping_neg()},
        @f* #inverse{-*self},
        bool #inverse{*self}
    ]
)]
trait Group<Op: Operator>: Loop<Op> {
    fn inverse(&self) -> Self;
}

#[batch_impl_only(
    #crate::tower::AbelianGroup:
    AbelianGroup<Additive> [@num, bool],
)]
trait AbelianGroup<Op: Operator>: Group<Op> {}

// ---- semiring ladder: Semiring → Ring → CommutativeRing → Field ----
// `bool` is the two-element field F₂ (xor as `+`, and as `*`).

#[batch_impl_only(
    #crate::tower::Semiring:
    Semiring<Additive, Multiplicative> [@num, bool],
)]
trait Semiring<Oa: Operator, Om: Operator>: Monoid<Oa> + Monoid<Om> {}

#[batch_impl_only(
    #crate::tower::Ring:
    Ring<Additive, Multiplicative> [@num,bool],
)]
trait Ring<Oa: Operator, Om: Operator>: Semiring<Oa, Om> + Group<Oa> {}

#[batch_impl_only(
    #crate::tower::CommutativeRing:
    CommutativeRing<Additive, Multiplicative> [@num,bool],
)]
trait CommutativeRing<Oa: Operator, Om: Operator>: Ring<Oa, Om> {}

#[batch_impl_only(
    #crate::tower::DivisionRing:
    DivisionRing<Additive, Multiplicative> [
        @f* #inv{1.0 / *self},
        bool #inv{*self}
    ]
)]
trait DivisionRing<Oa: Operator, Om: Operator>: Ring<Oa, Om> {
    fn inv(&self) -> Self;
}

#[batch_impl_only(
    Field<Additive, Multiplicative> [@f*, bool],
)]
trait Field<Oa: Operator, Om: Operator>: DivisionRing<Oa, Om> + CommutativeRing<Oa, Om> {}

// `bool` is the two-element field F₂: characteristic 2, order 2.

#[batch_impl_only(
    #crate::tower::FiniteField:
    FiniteField<Additive, Multiplicative> bool #characteristic{2} #order{2},
)]
trait FiniteField<Oa: Operator, Om: Operator>: Field<Oa, Om> {
    fn characteristic() -> u64;
    fn order() -> u64;
}

// ---- module level: every numeric is a module over itself ----

#[batch_impl_only(
    #crate::tower::Module:
    Module<Additive, Multiplicative> [
        [@u*, @i*] #Scalar{Self} #scale{s.wrapping_mul(v)},
        @f* #Scalar{Self} #scale{s * v},
        bool #Scalar{Self} #scale{*s && v},
    ]
)]
trait Module<Oa: Operator, Om: Operator>: AbelianGroup<Oa> {
    type Scalar;
    fn scale(s: &Self::Scalar, v: Self) -> Self;
}

// The integers' scalars (themselves) are rings, not fields — only the
// floats and the booleans (F₂) form vector spaces over themselves.

#[batch_impl_only(
    #crate::tower::VectorSpace:
    VectorSpace<Additive, Multiplicative> [@f*,bool] where{Self::Scalar: Field<Additive, Multiplicative>},
)]
trait VectorSpace<Oa: Operator, Om: Operator>: Module<Oa, Om> {}

// ---- free module: every numeric is a rank-1 free module over itself ----

#[batch_impl_only(
    #crate::tower::FreeModule:
    FreeModule<Additive, Multiplicative> [@num, bool] #rank{1}
        #basis_element{<Self as Monoid<Multiplicative>>::identity()}
        #coordinate{*self},
)]
trait FreeModule<Oa: Operator, Om: Operator>: Module<Oa, Om> {
    fn rank() -> usize;
    fn basis_element(_i: usize) -> Self;
    fn coordinate(&self, _i: usize) -> Self::Scalar;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tower::{AbelianGroup, DivisionRing, Field, Group, Magma, Monoid, Ring};

    fn add<T: Magma<Additive>>(a: T, b: T) -> T {
        <T as Magma<Additive>>::combine(&a, &b)
    }

    fn mul<T: Magma<Multiplicative>>(a: T, b: T) -> T {
        <T as Magma<Multiplicative>>::combine(&a, &b)
    }

    /// Every law of the additive ladder, checked for one concrete type.
    fn assert_additive_abelian<T>(a: T, b: T)
    where
        T: AbelianGroup<Additive> + Copy + PartialEq + core::fmt::Debug,
    {
        // associativity
        assert_eq!(add(add(a, b), a), add(a, add(b, a)));
        // identity
        let id = <T as Monoid<Additive>>::identity();
        assert_eq!(add(a, id), a);
        assert_eq!(add(id, a), a);
        // inverse
        let inv = <T as Group<Additive>>::inverse(&a);
        assert_eq!(add(a, inv), id);
        // commutativity
        assert_eq!(add(a, b), add(b, a));
    }

    /// Monoid laws of the multiplicative ladder (integers have no
    /// multiplicative inverses, so the ladder stops at Monoid there).
    fn assert_multiplicative_monoid<T>(a: T, b: T, c: T)
    where
        T: Monoid<Multiplicative> + Copy + PartialEq + core::fmt::Debug,
    {
        // associativity
        assert_eq!(mul(mul(a, b), c), mul(a, mul(b, c)));
        // identity
        let one = <T as Monoid<Multiplicative>>::identity();
        assert_eq!(mul(a, one), a);
        assert_eq!(mul(one, a), a);
    }

    /// Distributivity + multiplicative identity, the ring laws.
    fn assert_ring<T>(a: T, b: T, c: T)
    where
        T: Ring<Additive, Multiplicative> + Copy + PartialEq + core::fmt::Debug,
    {
        let one = <T as Monoid<Multiplicative>>::identity();
        assert_eq!(mul(a, one), a);
        assert_eq!(mul(one, a), a);
        // distributivity: a·(b+c) == a·b + a·c
        assert_eq!(mul(a, add(b, c)), add(mul(a, b), mul(a, c)));
    }

    /// Multiplicative inverse: a·a⁻¹ == 1 (and the reverse order).
    fn assert_field<T>(a: T)
    where
        T: Field<Additive, Multiplicative> + Copy + PartialEq + core::fmt::Debug,
    {
        let one = <T as Monoid<Multiplicative>>::identity();
        let inv = <T as DivisionRing<Additive, Multiplicative>>::inv(&a);
        assert_eq!(mul(a, inv), one);
        assert_eq!(mul(inv, a), one);
    }

    #[test]
    fn additive_ladder_holds_for_all_numerics() {
        assert_additive_abelian(3u8, 5u8);
        assert_additive_abelian(3u16, 5u16);
        assert_additive_abelian(3u32, 5u32);
        assert_additive_abelian(3u64, 5u64);
        assert_additive_abelian(3u128, 5u128);
        assert_additive_abelian(3usize, 5usize);
        assert_additive_abelian(3i8, 5i8);
        assert_additive_abelian(3i16, 5i16);
        assert_additive_abelian(3i32, 5i32);
        assert_additive_abelian(3i64, 5i64);
        assert_additive_abelian(3i128, 5i128);
        assert_additive_abelian(3isize, 5isize);
        assert_additive_abelian(3.5f32, 1.25f32);
        assert_additive_abelian(3.5f64, 1.25f64);
    }

    #[test]
    fn multiplicative_monoid_holds_for_all_numerics() {
        assert_multiplicative_monoid(3u8, 5u8, 7u8);
        assert_multiplicative_monoid(3u16, 5u16, 7u16);
        assert_multiplicative_monoid(3u32, 5u32, 7u32);
        assert_multiplicative_monoid(3u64, 5u64, 7u64);
        assert_multiplicative_monoid(3u128, 5u128, 7u128);
        assert_multiplicative_monoid(3usize, 5usize, 7usize);
        assert_multiplicative_monoid(3i8, 5i8, 7i8);
        assert_multiplicative_monoid(3i16, 5i16, 7i16);
        assert_multiplicative_monoid(3i32, 5i32, 7i32);
        assert_multiplicative_monoid(3i64, 5i64, 7i64);
        assert_multiplicative_monoid(3i128, 5i128, 7i128);
        assert_multiplicative_monoid(3isize, 5isize, 7isize);
        assert_multiplicative_monoid(3.0f32, 5.0f32, 7.0f32);
        assert_multiplicative_monoid(3.0f64, 5.0f64, 7.0f64);
    }

    #[test]
    fn ring_laws_hold_for_all_numerics() {
        assert_ring(2u8, 3u8, 4u8);
        assert_ring(2u16, 3u16, 4u16);
        assert_ring(2u32, 3u32, 4u32);
        assert_ring(2u64, 3u64, 4u64);
        assert_ring(2u128, 3u128, 4u128);
        assert_ring(2usize, 3usize, 4usize);
        assert_ring(2i8, 3i8, 4i8);
        assert_ring(2i16, 3i16, 4i16);
        assert_ring(2i32, 3i32, 4i32);
        assert_ring(2i64, 3i64, 4i64);
        assert_ring(2i128, 3i128, 4i128);
        assert_ring(2isize, 3isize, 4isize);
        assert_ring(2.0f32, 3.0f32, 4.0f32);
        assert_ring(2.0f64, 3.0f64, 4.0f64);
    }

    #[test]
    fn field_laws_hold_for_floats() {
        assert_field(2.0f32);
        assert_field(0.25f32);
        assert_field(-3.0f32);
        assert_field(2.0f64);
        assert_field(0.25f64);
        assert_field(-3.0f64);
    }

    #[test]
    fn bool_is_the_two_element_field() {
        // F₂: xor as +, and as *.
        assert_additive_abelian(true, false);
        assert_additive_abelian(false, false);
        assert_multiplicative_monoid(true, false, true);
        assert!(!add(true, true));
        assert!(mul(true, true));
        assert!(!<bool as Monoid<Additive>>::identity());
        assert!(<bool as Monoid<Multiplicative>>::identity());
        // Every nonzero element (true) has an inverse: itself.
        assert!(<bool as DivisionRing<Additive, Multiplicative>>::inv(&true));
    }

    #[test]
    fn bool_is_finite_field_f2() {
        use crate::tower::FiniteField;
        assert_eq!(<bool as FiniteField<Additive, Multiplicative>>::characteristic(), 2);
        assert_eq!(<bool as FiniteField<Additive, Multiplicative>>::order(), 2);
    }
}
